### ISSUE TITLE
Thymeleaf 수정 후 매핑 확인하기

### ISSUE THREAD

**Issue by kokojihye** [tutorLink-SYU-Capstone2023/TutorLink_Backend#22]
## Description 💭
당장 백엔드는 기능 구현 확인하기 위해 thymeleaf를 사용하고 있는데, global navigation bar(이하 gnb)가 필요할 것 같아서 타임리프에 추가한다.

## To-do ✔️
- [x] gnb 작성 후 필요한 부분에 코드 추가
- [x] html 파일 명이 식별하기 힘들어서 일부 수정도 함께 할 예정
- [x] 연결된 controller도 수정해 매핑에 문제 없는 것까지 확인하기
