### ISSUE TITLE
게시글 삭제 JPA로 구현하기

### ISSUE THREAD

**Issue by kokojihye** [tutorLink-SYU-Capstone2023/TutorLink_Backend#5]
## Description 💭
작성된 게시글을 삭제합니다.

## To-do ✔️
- [ ] 게시글 작성자만 게시글을 삭제할 수 있도록 삭제 기능을 구현해야 합니다.
- [ ] 삭제 일자가 게시글 테이블에 저장되는지 확인해야 합니다.
- [ ] 테스트 코드를 작성해 게시글이 정상 삭제되는지 확인합니다.

## ETC 🌷

**Comment by kokojihye** [comment]
일단 냅다 DB에서 삭제되게 구현은 했습니다. 
삭제 처리시 데이터베이스에서 삭제되는 것이 아닌 화면상에 노출되지 않도록 처리하겠습니다
